# Generated by Django 2.2.23 on 2021-06-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakup',
            name='product',
            field=models.ForeignKey(help_text='Produkt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AddField(
            model_name='zakup',
            name='quantity',
            field=models.IntegerField(default=1, help_text='ilość'),
        ),
        migrations.DeleteModel(
            name='ZakupProduktu',
        ),
    ]
