# Generated by Django 2.2.23 on 2021-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210601_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=100, help_text='Cena', null=True),
        ),
        migrations.AlterField(
            model_name='zakup',
            name='quantity',
            field=models.FloatField(default=1.0, help_text='ilość', null=True),
        ),
    ]
