# Generated by Django 2.2.23 on 2021-06-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210601_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nazwa produktu', max_length=200),
        ),
    ]
