# Generated by Django 2.2.23 on 2021-06-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210601_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='zakup',
            name='price',
            field=models.FloatField(default=100, help_text='Cena', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nazwa produktu', max_length=200, unique=True),
        ),
    ]
